name: Claude Code PR Review

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  claude-code-review:
    if: |
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Please review this TypeScript OAuth2 server pull request with focus on:

            1. **Breaking Changes**:
               - Check for any changes to public APIs, interfaces, or exported functions
               - Verify that existing method signatures haven't changed
               - Look for removals of public methods or properties
               - Check if any changes affect backward compatibility

            2. **Test Coverage**:
               - Ensure new code has corresponding test files using Vitest
               - Verify test files follow the existing pattern (*.spec.ts)
               - Check that new features have adequate test coverage
               - Ensure edge cases and error scenarios are tested

            3. **Documentation Updates**:
               - Check if changes to public APIs are documented in /docs
               - Verify that new features have documentation
               - Ensure README.md is updated if new functionality is added
               - Check that JSDoc comments are present for public methods

            4. **Code Quality**:
               - Ensure TypeScript strict mode compliance
               - Check for proper error handling using OAuthException
               - Verify imports use .js extensions as per project standards
               - Confirm snake_case file naming convention is followed

            Please provide specific feedback on any issues found and suggest improvements.
